application: shaoxin12345
version: 1
runtime: python27
api_version: 1
threadsafe: no



handlers:

- url: /_ah/mail/.+
  script: handle_incoming_email.py
  login: admin

- url: /upload/.*
  script: do_openid_login.py

- url: /static
  static_dir: static

- url: /.*
  script: main.application


inbound_services:
- mail


libraries:

- name: django
  version: "1.4"


env_variables:
  DJANGO_SETTINGS_MODULE: 'questionAnswer.settings'
